// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2010, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================


#ifndef SEQAN_HEADER_SEQUENCE_JOURNALED_MULTIPLE_GENERATED_FORWARDS_H 
#define SEQAN_HEADER_SEQUENCE_JOURNALED_MULTIPLE_GENERATED_FORWARDS_H 

//////////////////////////////////////////////////////////////////////////////
// NOTE: This file is automatically generated by build_forwards.py
//       Do not edit this file manually!
//////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////
// CLASSES
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// ExtendedScore_

struct ExtendedScore_;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(28)

//____________________________________________________________________________
// JournalTraceDescriptor

template <typename TString> struct JournalTraceDescriptor;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(42)

//____________________________________________________________________________
// MaxCompression_

struct MaxCompression_;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(34)

//____________________________________________________________________________
// SimpleJoin_

struct SimpleJoin_;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(31)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// Group

template <typename TSet, typename TGroupSpec> class Group;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(34)

//____________________________________________________________________________
// GroupBasic_

struct GroupBasic_;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(29)

//____________________________________________________________________________
// GroupLabel

template <typename TGroup > struct GroupLabel;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(167)

//____________________________________________________________________________
// GroupMembers

template <typename TGroup> struct GroupMembers;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(148)

//____________________________________________________________________________
// InfoNode

template <typename TPosition_, typename TSize_, typename TInsertBuff_> struct InfoNode;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(39)

//____________________________________________________________________________
// JournalSetBasic_

struct JournalSetBasic_;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(28)

//____________________________________________________________________________
// Listener

template <typename T> struct Listener;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/listener_basic.h"(31)

//____________________________________________________________________________
// StringSetGroups

template <typename TSet> struct StringSetGroups;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(33)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// TYPEDEFS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// ExtendedScore

typedef Tag<ExtendedScore_> const ExtendedScore;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(29)

//____________________________________________________________________________
// MaxCompression

typedef Tag<MaxCompression_> const MaxCompression;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(35)

//____________________________________________________________________________
// SimpleJoin

typedef Tag<SimpleJoin_> const SimpleJoin;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(32)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// GroupBasic

typedef Tag<GroupBasic_> const GroupBasic;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(30)

//____________________________________________________________________________
// JournalSetBasic

typedef Tag<JournalSetBasic_> const JournalSetBasic;       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(29)

} //namespace seqan


//////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
//////////////////////////////////////////////////////////////////////////////

namespace SEQAN_NAMESPACE_MAIN {

//____________________________________________________________________________
// MaxCompression

template <typename TValue, typename TGroupId, typename TJournalId, typename TScoreValue, typename TScoreSpec, typename TStrategy> void join(StringSet<TValue, Owner<JournalSetBasic> > & me, TGroupId groupId, TJournalId journalId, Score<TScoreValue, TScoreSpec> const & score , TStrategy const & strategy );       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(59)

//____________________________________________________________________________
// _alignTracePrint

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TStringSet, typename TId, typename TPos, typename TTraceValue> inline void _alignTracePrint(JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > & me, TStringSet const & str, TId const id1, TPos const pos1, TId const, TPos const pos2, TPos const segLen, TTraceValue const tv);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(248)

//____________________________________________________________________________
// appliesTo

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline bool appliesTo(String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & journal, String <TValue, THostSpec> const & reference);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(80)

//____________________________________________________________________________
// applyOperations

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline void applyOperations(String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > & journal, String<TValue, THostSpec> const & newHost, JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > const & traceDescr);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(90)

//____________________________________________________________________________
// constructAndSetJournalTree

template <typename TValue, typename THostSpec, typename TBuffSpec> inline void constructAndSetJournalTree(String<TValue, Journaled<THostSpec, SortedArray, TBuffSpec> > & journalSeq, JournalTraceDescriptor<String<TValue, Journaled<THostSpec, SortedArray, TBuffSpec> > > const & traceDescr);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(313)
template <typename TValue, typename THostSpec, typename TBuffSpec> inline void constructAndSetJournalTree(String<TValue, Journaled<THostSpec, UnbalancedTree, TBuffSpec> > & seq, JournalTraceDescriptor<String<TValue, Journaled<THostSpec, UnbalancedTree, TBuffSpec> > > const & traceDescr);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(324)

//____________________________________________________________________________
// defaultMaxCompressionScore

template <typename TValue> inline Score<TValue, ExtendedScore> defaultMaxCompressionScore();       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(43)

//____________________________________________________________________________
// getInsertionBuffer

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline String<TValue, TBuffSpec> & getInsertionBuffer(JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(193)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline String<TValue, TBuffSpec> const & getInsertionBuffer(JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(205)

//____________________________________________________________________________
// getTrace

template <typename TString> inline String <typename Value<JournalTraceDescriptor<TString> >::Type> & getTrace(JournalTraceDescriptor<TString > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(148)
template <typename TString> inline String<typename Value<JournalTraceDescriptor<TString> >::Type> const & getTrace(JournalTraceDescriptor<TString> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(158)

//____________________________________________________________________________
// getTraceReverse

template <typename TString> inline String <typename Value<JournalTraceDescriptor<TString> >::Type> & getTraceReverse(JournalTraceDescriptor<TString> & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(170)
template <typename TString> inline String <typename Value<JournalTraceDescriptor<TString> >::Type> const & getTraceReverse(JournalTraceDescriptor<TString> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(182)

//____________________________________________________________________________
// internalJoin_

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TScore> float internalJoin_(String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > & journal, String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & refJournal, TScore const & score, MaxCompression const &);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_max_compression.h"(40)

//____________________________________________________________________________
// length

template <typename TJournal> inline typename Size<JournalTraceDescriptor<TJournal> >::Type length(JournalTraceDescriptor<TJournal> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(301)

//____________________________________________________________________________
// operator<<

template <typename TStream, typename TJournal> TStream & operator<<(TStream & stream, JournalTraceDescriptor<TJournal> const & obj);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(284)

//____________________________________________________________________________
// scoreGapExtendDelete

template <typename TValue> inline TValue scoreGapExtendDelete(Score<TValue, ExtendedScore> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(108)

//____________________________________________________________________________
// scoreGapExtendHorizontal

template <typename TValue, typename TPos1, typename TPos2, typename TStr1, typename TStr2> inline TValue scoreGapExtendHorizontal(Score<TValue, ExtendedScore> const & me, TPos1, TPos2, TStr1 const &, TStr2 const &);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(156)

//____________________________________________________________________________
// scoreGapExtendInsert

template <typename TValue> inline TValue scoreGapExtendInsert(Score<TValue, ExtendedScore> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(92)

//____________________________________________________________________________
// scoreGapExtendVertical

template <typename TValue, typename TPos1, typename TPos2, typename TStr1, typename TStr2> inline TValue scoreGapExtendVertical(Score<TValue, ExtendedScore> const & me, TPos1, TPos2, TStr1 const &, TStr2 const &);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(132)

//____________________________________________________________________________
// scoreGapOpenDelete

template <typename TValue> inline TValue scoreGapOpenDelete(Score<TValue, ExtendedScore> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(100)

//____________________________________________________________________________
// scoreGapOpenHorizontal

template <typename TValue, typename TPos1, typename TPos2, typename TStr1, typename TStr2> inline TValue scoreGapOpenHorizontal(Score<TValue, ExtendedScore> const & me, TPos1, TPos2, TStr1 const &, TStr2 const &);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(144)

//____________________________________________________________________________
// scoreGapOpenInsert

template <typename TValue> inline TValue scoreGapOpenInsert(Score<TValue, ExtendedScore> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(84)

//____________________________________________________________________________
// scoreGapOpenVertical

template <typename TValue, typename TPos1, typename TPos2, typename TStr1, typename TStr2> inline TValue scoreGapOpenVertical(Score<TValue, ExtendedScore> const & me, TPos1, TPos2, TStr1 const &, TStr2 const &);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(120)

//____________________________________________________________________________
// scoreMatch

template <typename TValue> inline TValue scoreMatch(Score<TValue, ExtendedScore> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(68)

//____________________________________________________________________________
// scoreMismatch

template <typename TValue> inline TValue scoreMismatch(Score<TValue, ExtendedScore> const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/score_journal.h"(76)

//____________________________________________________________________________
// updateGroup

template <typename TValue, typename TGroupId, typename TJournalId> inline void updateGroup(StringSet<TValue, Owner<JournalSetBasic> > & me, TGroupId groupId, TJournalId journalId);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_base.h"(108)

//____________________________________________________________________________
// value

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline typename Reference<JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > >::Type value(JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > & me, typename Position<JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > >::Type const pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(217)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline typename Reference<JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > const >::Type value(JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > const & me, typename Position<JournalTraceDescriptor<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > > >::Type const pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_join_trace.h"(229)

} //namespace SEQAN_NAMESPACE_MAIN
//////////////////////////////////////////////////////////////////////////////

namespace seqan {

//____________________________________________________________________________
// MaxCompression

template <typename TValue, typename TPosition, typename TScore, typename TStrategy> void merge(StringSet<TValue, Owner<JournalSetBasic> > & me, TPosition const & targetGrpPos, TPosition const & sourceGrpPos, TScore const & score , TStrategy const & tag );       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(77)
template <typename TValue, typename TPosition, typename TScore, typename TStrategy> void join(StringSet<TValue, Owner<JournalSetBasic> > & me, TPosition & groupPos, TPosition & jrnPos, TScore const & score , TStrategy const & tag );       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(101)

//____________________________________________________________________________
// adaptGroupMembers_

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> void adaptGroupMembers_(StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & set, String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & source);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(138)

//____________________________________________________________________________
// appendValue

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TExpand> void appendValue(StringSet<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & me, String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & newElement, Tag<TExpand> const & tag);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(166)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TExpand> void appendValue(StringSet<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & me, String<TValue, THostSpec> const & newElement, Tag<TExpand> const & tag);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(198)
template <typename TSet, typename TGroupSpec, typename TExpand > inline void appendValue(Group <TSet, TGroupSpec> & me, typename Position <Group<TSet, TGroupSpec> >::Type const & memberId, Tag < TExpand > const & tag);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(342)

//____________________________________________________________________________
// appliesTo

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec> inline bool appliesTo(String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & target, String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & source);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(126)

//____________________________________________________________________________
// assignValue

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TExpand> void assignValue(StringSet<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & me, String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > & newValue, typename Position<StringSet<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > >::Type const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(228)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TExpand> void assignValue(StringSet<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & me, String<TValue, THostSpec> & newValue, typename Position<StringSet<String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > >::Type const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(275)

//____________________________________________________________________________
// clear

template <typename TValue> inline void clear(StringSet<TValue, Owner<JournalSetBasic> > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(336)
template <typename TSet, typename TGroupSpec > inline void clear(Group < TSet, TGroupSpec > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(328)

//____________________________________________________________________________
// computeSmallestJournal_

template <typename TScoreValue, unsigned DIMENSION, typename TString> TScoreValue computeSmallestJournal_(Matrix<TScoreValue, DIMENSION> & diag_matrix_, Matrix<TScoreValue, DIMENSION> & vert_matrix_, Matrix<TScoreValue, DIMENSION> & hori_matrix_, TString const & target_, TString const & source_, Score<TScoreValue, ExtendedScore> const & score_);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(767)

//____________________________________________________________________________
// disjoin

template <typename TGroup, typename TPosition > inline bool disjoin(TGroup & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(472)

//____________________________________________________________________________
// erase

template <typename TSet, typename TGroupSpec, typename TPosition> inline void erase(Group < TSet, TGroupSpec > & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(462)

//____________________________________________________________________________
// findGroup_

template <typename TValue, typename TSetSpec> inline typename Position<StringSet<TValue, Owner<TSetSpec> > const >::Type findGroup_(StringSet<TValue, Owner<TSetSpec> > const & me, typename Position<StringSet<TValue, Owner<TSetSpec> > const >::Type const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(353)

//____________________________________________________________________________
// findPosition_

template <typename TJournalGroup, typename TPosition > inline typename Size < TJournalGroup >::Type findPosition_(TJournalGroup const & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(368)

//____________________________________________________________________________
// getGroupLabel

template <typename TJournalSet, typename TGroupSpec> inline String<char> & getGroupLabel(Group<TJournalSet, TGroupSpec> & group);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(219)
template <typename TJournalSet, typename TGroupSpec> inline String<char> const & getGroupLabel(Group<TJournalSet, TGroupSpec> const & group);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(230)

//____________________________________________________________________________
// getGroupMap

template <typename TValue> inline String<typename Position<StringSet<TValue, Owner<JournalSetBasic> > >::Type> & getGroupMap(StringSet<TValue, Owner<JournalSetBasic> > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(450)
template <typename TValue> inline String<typename Position<StringSet<TValue, Owner<JournalSetBasic> > >::Type> const & getGroupMap(StringSet<TValue, Owner<JournalSetBasic> > const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(458)

//____________________________________________________________________________
// getGroupMembers

template <typename TJournalSet, typename TGroupSpec> inline typename GroupMembers<Group<TJournalSet,TGroupSpec> >::Type & getGroupMembers(Group<TJournalSet, TGroupSpec> & group);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(275)
template <typename TJournalSet, typename TGroupSpec> inline typename GroupMembers<Group<TJournalSet,TGroupSpec> const>::Type & getGroupMembers(Group<TJournalSet, TGroupSpec> const & group);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(283)

//____________________________________________________________________________
// getGroupReference

template <typename TJournalSet, typename TGroupSpec> inline typename Position<Group<TJournalSet, TGroupSpec> >::Type getGroupReference( Group<TJournalSet, TGroupSpec> & group);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(247)
template <typename TJournalSet, typename TGroupSpec> inline typename Position<Group<TJournalSet, TGroupSpec> const>::Type getGroupReference( Group<TJournalSet, TGroupSpec> const & group);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(255)

//____________________________________________________________________________
// getGroups

template <typename TValue> inline typename StringSetGroups<StringSet<TValue, Owner<JournalSetBasic> > >::Type & getGroups(StringSet<TValue, Owner<JournalSetBasic> > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(434)
template <typename TValue> inline typename StringSetGroups<StringSet<TValue, Owner<JournalSetBasic> > >::Type const & getGroups(StringSet<TValue, Owner<JournalSetBasic> > const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(442)

//____________________________________________________________________________
// getStrings

template <typename TValue> inline String<TValue> & getStrings(StringSet<TValue, Owner<JournalSetBasic> > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(418)
template <typename TValue> inline String<TValue> const & getStrings(StringSet<TValue, Owner<JournalSetBasic> > const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(426)

//____________________________________________________________________________
// internalJoin_

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TScore, typename TStrategy> void internalJoin_(String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > & source, String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & target, TScore const & , TStrategy const & tag);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(716)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TScore> void internalJoin_(String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > & source, String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & target, TScore const & , SimpleJoin const & );       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(729)

//____________________________________________________________________________
// internalMerge_

template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TScore, typename TStrategy> void internalMerge_(StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & set, String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & target, String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > & source, TScore const & score, TStrategy const & tag);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(168)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TScore> void internalMerge_(StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & set, Group <StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> >, GroupBasic > const & target, Group <StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> >, GroupBasic > & source, TScore const & , SimpleJoin const & );       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(179)
template <typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TScore> void internalMerge_(StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> > & set, Group <StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> >, GroupBasic > const & target, Group <StringSet< String <TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> >, Owner<JournalSetBasic> >, GroupBasic > & source, TScore const & , MaxCompression const & );       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(205)

//____________________________________________________________________________
// isMember

template <typename TJournalGroup, typename TPosition > inline bool isMember(TJournalGroup const & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(424)

//____________________________________________________________________________
// isReference

template <typename TSet, typename TGroupSpec, typename TPosition > inline bool isReference(Group < TSet, TGroupSpec> & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(354)

//____________________________________________________________________________
// join

template <typename TJournalGroup, typename TPosition > inline bool join(TJournalGroup & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(439)
template <typename TJournalGroup, typename TPosition, typename TExpand > inline bool join(TJournalGroup & me, TPosition const & pos, Tag<TExpand> const & tag);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(449)

//____________________________________________________________________________
// length

template <typename TSet, typename TGroupSpec > inline typename Size < Group < TSet, TGroupSpec > const >::Type length( Group < TSet, TGroupSpec > const & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(385)

//____________________________________________________________________________
// notifyModified

template <typename TListener, typename TValue> void notifyModified(TListener const & listener, TValue * object);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/listener_basic.h"(40)

//____________________________________________________________________________
// operator!=

template <typename TJournalSet, typename TGroupSpec> inline bool operator!=(Group<TJournalSet, TGroupSpec> const & lObject, Group<TJournalSet, TGroupSpec> const & rObject);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(317)

//____________________________________________________________________________
// operator==

template <typename TJournalSet, typename TGroupSpec> inline bool operator==(Group<TJournalSet, TGroupSpec> const & lObject, Group<TJournalSet, TGroupSpec> const & rObject);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(294)

//____________________________________________________________________________
// recordDeletion_

template <typename TInfoNodes, typename TPos, typename TPos2, typename TInsBuff> inline void recordDeletion_(TInfoNodes & nodes, TPos & endPos, TPos & delLength, TPos2 & delta, TInsBuff & );       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(1083)

//____________________________________________________________________________
// recordInsertion_

template <typename TInfoNodes, typename TPos, typename TPos2, typename TInsBuff> inline void recordInsertion_(TInfoNodes & nodes, TPos & beginPos, TPos2 & delta, TInsBuff & insBuff);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(1060)

//____________________________________________________________________________
// rename

template <typename TSet, typename TGroupSpec > inline void rename(Group < TSet, TGroupSpec > & me, String <char> const & newLabel);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(415)

//____________________________________________________________________________
// resize

template <typename TValue, typename TSize> inline void resize(StringSet<TValue, Owner<JournalSetBasic> > & me, TSize const & newSize);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(325)

//____________________________________________________________________________
// resolveGroupMap_

template <typename TValue> inline void resolveGroupMap_(StringSet<TValue, Owner<JournalSetBasic> > & me);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(373)

//____________________________________________________________________________
// setGroupLabel

template <typename TJournalSet, typename TGroupSpec> inline void setGroupLabel(Group<TJournalSet, TGroupSpec> & group, String<char> const & newLabel);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(208)

//____________________________________________________________________________
// setGroupMembers

template <typename TJournalSet, typename TGroupSpec> inline void setGroupMembers(Group<TJournalSet, TGroupSpec > & group, String<typename Position<Group<TJournalSet, TGroupSpec> >::Type> newMembers);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(263)

//____________________________________________________________________________
// setGroupReference

template <typename TJournalSet, typename TGroupSpec> inline void setGroupReference(Group<TJournalSet, TGroupSpec> & group, typename Position<Group<TJournalSet, TGroupSpec> >::Type const & refId);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(239)

//____________________________________________________________________________
// splitNode

template <typename TCargo> inline void splitNode(JournalEntries<TCargo, UnbalancedTree> & tree, typename Position<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & virtualPos, typename Position<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & physicalBeginPos, typename Size<typename JournalEntries<TCargo, UnbalancedTree>::TNode>::Type const & length);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(648)

//____________________________________________________________________________
// swap

template <typename TSet, typename TGroupSpec > inline bool swap( Group < TSet, TGroupSpec > & me, typename Position<Group<TSet, TGroupSpec> >::Type const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(397)

//____________________________________________________________________________
// synchronizeJournalTrees_

template <typename TValue, typename THostSpec, typename TBuffSpec> void synchronizeJournalTrees_(String<TValue, Journaled<THostSpec, SortedArray, TBuffSpec> > & target, String<TValue, Journaled<THostSpec, SortedArray, TBuffSpec> > & source);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(238)
template <typename TValue, typename THostSpec, typename TBuffSpec> void synchronizeJournalTrees_(String<TValue, Journaled<THostSpec, UnbalancedTree, TBuffSpec> > const & target, String<TValue, Journaled<THostSpec, UnbalancedTree, TBuffSpec> > & source);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(446)

//____________________________________________________________________________
// traceSmallestJournal_

template <typename TScoreValue, unsigned DIMENSION, typename TValue, typename THostSpec, typename TJournalSpec, typename TBuffSpec, typename TInfoNodes> void traceSmallestJournal_(Matrix<TScoreValue, DIMENSION> & diagMatrix, Matrix<TScoreValue, DIMENSION> & vertMatrix, Matrix<TScoreValue, DIMENSION> & horiMatrix, String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & target, String<TValue, Journaled<THostSpec, TJournalSpec, TBuffSpec> > const & source, TInfoNodes & tmpNodes, Score<TScoreValue, ExtendedScore> const & score);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_util.h"(915)

//____________________________________________________________________________
// value

template <typename TValue, typename TPosition> inline typename Reference<StringSet<TValue, Owner<JournalSetBasic> > >::Type value(StringSet<TValue, Owner<JournalSetBasic> > & me, TPosition const pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(145)
template <typename TValue, typename TPosition> inline typename Reference<StringSet<TValue, Owner<JournalSetBasic> > const >::Type value(StringSet<TValue, Owner<JournalSetBasic> > const & me, TPosition const pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_basic.h"(156)
template <typename TSet, typename TGroupSpec, typename TPosition> inline typename Reference<Group<TSet, TGroupSpec> >::Type value(Group<TSet,TGroupSpec> & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(187)
template <typename TSet, typename TGroupSpec, typename TPosition> inline typename Reference<Group<TSet, TGroupSpec> const>::Type value(Group<TSet, TGroupSpec> const & me, TPosition const & pos);       	// "F:/Development/workspace_genomes_per_email/seqan/projects/library/seqan/sequence_journaled_multiple/string_set_journaled_group.h"(196)

} //namespace seqan

#endif

