#!/usr/bin/env python
"""Execute the tests for bs_mason.

The golden test outputs are generated by the script generate_outputs.sh.

You have to give the root paths to the source and the binaries as arguments to
the program.  These are the paths to the directory that contains the 'projects'
directory.

Usage:  run_tests.py SOURCE_ROOT_PATH BINARY_ROOT_PATH
"""
import logging
import os.path
import sys

# Automagically add util/py_lib to PYTHONPATH environment variable.
path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..',
                                    '..', '..', '..', 'util', 'py_lib'))
sys.path.insert(0, path)

import seqan.app_tests as app_tests

def main(source_base, binary_base):
    """Main entry point of the script."""

    print 'Executing test for bs_mason'
    print '========================='
    print

    ph = app_tests.TestPathHelper(
        source_base, binary_base,
        'sandbox/krakau/apps/bs_mason/tests')  # tests dir
    
    # ============================================================
    # Auto-detect the binary path.
    # ============================================================

    path_to_program = app_tests.autolocateBinary(
      binary_base, 'sandbox/krakau/apps/bs_mason', 'bs_mason')

    # ============================================================
    # Built TestConf list.
    # ============================================================

    # Build list with TestConf objects, analoguely to how the output
    # was generated in generate_outputs.sh.
    conf_list = []

    # We prepare a list of transforms to apply to the output files: Strip the
    # running times from output.
    transforms = [
        app_tests.RegexpReplaceTransform(r'Finished haplotype creation in [0-9.]+s',
                                         r'Finished haplotype creation in <cut out>s',
                                         left=True, right=True),
        ]

    # ============================================================
    # Simulate methylation rates
    # ============================================================

    # App TestConf objects to conf_list, just like this for each
    # test you want to run.
    conf = app_tests.TestConf(
        program=path_to_program,
        redir_stdout=ph.outFile('illumina-se-adeno-N100-n36.stdout'),
        args=['illumina_bs', '-N', '100', '-n', '36', '-s', '0', '-rnp', 'read', 
              '-o', ph.outFile('illumina-se-adeno-N100-n36.fasta'),
              ph.inFile('adeno-genome.fa')],
        to_diff=[(ph.inFile('illumina-se-adeno-N100-n36.fasta'),
                  ph.outFile('illumina-se-adeno-N100-n36.fasta')),
                 (ph.inFile('illumina-se-adeno-N100-n36.stdout'),
                  ph.outFile('illumina-se-adeno-N100-n36.stdout'),
                  transforms)])
    conf_list.append(conf)

    conf = app_tests.TestConf(
        program=path_to_program,
        redir_stdout=ph.outFile('hg18_21_tiny-se-N100-n36.stdout'),
        args=['illumina_bs', '-N', '100', '-n', '36', '-s', '0', '-rnp', 'read', 
              '-o', ph.outFile('hg18_21_tiny-se-N100-n36.fasta'),
              ph.inFile('hg18_21_tiny.fa')],
        to_diff=[(ph.inFile('hg18_21_tiny-se-N100-n36.fasta'),
                  ph.outFile('hg18_21_tiny-se-N100-n36.fasta')),
                 (ph.inFile('hg18_21_tiny-se-N100-n36.stdout'),
                  ph.outFile('hg18_21_tiny-se-N100-n36.stdout'),
                  transforms)])
    conf_list.append(conf)

    # paired-end
    conf = app_tests.TestConf(
        program=path_to_program,
        redir_stdout=ph.outFile('hg18_21_tiny-pe-N100-n36.stdout'),
        args=['illumina_bs', '-mp', '-N', '100', '-n', '36', '-s', '0', '-rnp', 'read', 
              '-o', ph.outFile('hg18_21_tiny-pe-N100-n36.fasta'),
              ph.inFile('hg18_21_tiny.fa')],
        to_diff=[(ph.inFile('hg18_21_tiny-pe-N100-n36_1.fasta'),
                  ph.outFile('hg18_21_tiny-pe-N100-n36_1.fasta')),
                 (ph.inFile('hg18_21_tiny-pe-N100-n36_2.fasta'),
                  ph.outFile('hg18_21_tiny-pe-N100-n36_2.fasta')),
                 (ph.inFile('hg18_21_tiny-pe-N100-n36.stdout'),
                  ph.outFile('hg18_21_tiny-pe-N100-n36.stdout'),
                  transforms)])
    conf_list.append(conf)


    # ============================================================
    # Use given methylation rates
    # ============================================================


    conf = app_tests.TestConf(
        program=path_to_program,
        redir_stdout=ph.outFile('hg18_21_tiny-se-N100-n36-umr.stdout'),
        args=['illumina_bs', '-N', '100', '-n', '36', '-s', '0', '-rnp', 'read', 
              '-o', ph.outFile('hg18_21_tiny-se-N100-n36-umr.fasta'),
              '-umr', '-mr' , ph.inFile('h1_21_tiny_methLevel.txt'),
              ph.inFile('hg18_21_tiny.fa')],
        to_diff=[(ph.inFile('hg18_21_tiny-se-N100-n36-umr.fasta'),
                  ph.outFile('hg18_21_tiny-se-N100-n36-umr.fasta')),
                 (ph.inFile('hg18_21_tiny-se-N100-n36-umr.stdout'),
                  ph.outFile('hg18_21_tiny-se-N100-n36-umr.stdout'),
                  transforms)])
    conf_list.append(conf)

    # paired-end
    conf = app_tests.TestConf(
        program=path_to_program,
        redir_stdout=ph.outFile('hg18_21_tiny-pe-N100-n36-umr.stdout'),
        args=['illumina_bs', '-mp', '-N', '100', '-n', '36', '-s', '0', '-rnp', 'read', 
              '-o', ph.outFile('hg18_21_tiny-pe-N100-n36-umr.fasta'),
              '-umr', '-mr' , ph.inFile('h1_21_tiny_methLevel.txt'),
              ph.inFile('hg18_21_tiny.fa')],
        to_diff=[(ph.inFile('hg18_21_tiny-pe-N100-n36-umr_1.fasta'),
                  ph.outFile('hg18_21_tiny-pe-N100-n36-umr_1.fasta')),
                 (ph.inFile('hg18_21_tiny-pe-N100-n36-umr_2.fasta'),
                  ph.outFile('hg18_21_tiny-pe-N100-n36-umr_2.fasta')),
                 (ph.inFile('hg18_21_tiny-pe-N100-n36-umr.stdout'),
                  ph.outFile('hg18_21_tiny-pe-N100-n36-umr.stdout'),
                  transforms)])
    conf_list.append(conf)


    # ============================================================
    # Execute the tests.
    # ============================================================
    failures = 0
    for conf in conf_list:
        res = app_tests.runTest(conf)
        # Output to the user.
        print ' '.join(['bs_mason'] + conf.args),
        if res:
             print 'OK'
        else:
            failures += 1
            print 'FAILED'

    # Cleanup.
    ph.deleteTempDir()

    print '=============================='
    print '     total tests: %d' % len(conf_list)
    print '    failed tests: %d' % failures
    print 'successful tests: %d' % (len(conf_list) - failures)
    print '=============================='
    # Compute and return return code.
    return failures != 0


if __name__ == '__main__':
    sys.exit(app_tests.main(main))
